<?php
/*
 * Plugin class
 *
 * auto-generated by the sfDoctrine plugin
 * creation date: 2007-04-01 18:02:50
 */
class PluginsfGuardGroup extends BasesfGuardGroup
{
    public function __toString()
    {
        return $this->get( 'name' );
    }
}
