<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserTable extends Doctrine_Table
{
  public static function retrieveByUsername($username, $isActive = true)
  {
    return Doctrine::getTable('sfGuardUser')->createQuery('u')
            ->where('u.username = ?', $username)
            ->addWhere('u.is_active = ?', $isActive)
            ->fetchOne();
  }
}
